apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80           # Service port (internal)
      targetPort: 80     # Pod container port
      nodePort: 30080    # External port (accessible via browser)

