apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Service port inside cluster
      targetPort: 80  # Pod port
  type: NodePort

